### PR TITLE
fix: use ad-hoc user for rest api authentication

### PR DESCRIPTION
**Pull request by mattdibi**
See: https://eurotech.atlassian.net/browse/ECESF-8351

Tested working with the following test preconditions:

image

### CODE REVIEW

**Comment by MMaiero** [comment]
@mattdibi Maybe this information on the usage should be put in a respective readme file. So that it does not get lost once we merge this PR

**Comment by MMaiero** [comment]
Does the zip file need to be uploaded as well?

**Comment by mattdibi** [comment]
> @mattdibi Maybe this information on the usage should be put in a respective readme file. So that it does not get lost once we merge this PR

Oh sorry I missed that. I'll update them ASAP

**Comment by mattdibi** [comment]
> Does the zip file need to be uploaded as well?

I might need some clarification here.

**Comment by mattdibi** [comment]
> > Does the zip file need to be uploaded as well?
> 
> I might need some clarification here.

Nevermind I saw that I uploaded the .zip file by mistake. Sorry :D

**Review by MMaiero — APPROVED** [review]

**Pull request merged**
